site_name: Github Organization Guidelines
nav:
  - Home: ./index.md 
  - General Guidelines: ./general-guidelines.md
  - Official GitHub Repositories: ./official-git-repo.md
  - Tips for Git: ./tips-for-git.md
  - External Docs and Useful Links: ./external-docs-useful-links.md
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: readthedocs
  logo: ./assets/logo_base_horizontal_nolabname.png
  palette:
    primary: black
    accent: indigo