site_name: Ifremer-Lirmm Lab
nav:
  - Home: ./index.md 
  - Official GitHub Repositories: ./official-git-repo.md
  - GitHub Organization Guidelines: ./general-guidelines.md
  - The Team and Research Activities: ./team-research.md
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: readthedocs
  logo: ./assets/logo_base_horizontal_nolabname.png
  palette:
    primary: black
    accent: indigo